echo 17 > /sys/class/gpio/unexport
echo 27 > /sys/class/gpio/unexport
echo 26 > /sys/class/gpio/unexport
echo 14 > /sys/class/gpio/unexport
echo 19 > /sys/class/gpio/unexport
echo 15 > /sys/class/gpio/unexport
echo 23 > /sys/class/gpio/unexport
echo 13 > /sys/class/gpio/unexport
echo 6 > /sys/class/gpio/unexport
echo 18 > /sys/class/gpio/unexport
echo 21 > /sys/class/gpio/unexport
echo 8 > /sys/class/gpio/unexport
echo 25 > /sys/class/gpio/unexport
echo 20 > /sys/class/gpio/unexport
echo 7 > /sys/class/gpio/unexport
echo 12 > /sys/class/gpio/unexport
echo 24 > /sys/class/gpio/unexport
echo 16 > /sys/class/gpio/unexport
