#include "fake6502.c"

#define W65C02S

#ifdef W65C02S
static void absi ( context_t *c ) { // (absolute)
    c->ea = mem_read16 ( c, c->pc );
    c->ea = mem_read16 ( c, c->ea );
    c->pc += 2;
}

static void rel_zp ( context_t *c ) {
    abso ( c );
}

// **************************************************************************************
void bbr0 ( context_t *c ) {
    uint16_t rel = ( c->ea & 0xFF00 ) >> 8;
    uint16_t zp = c->ea & 0x00FF;

    if ( rel & 0x80 ) rel |= 0xFF00;
    c->ea = c->pc + rel;

    if ( ( zp & 0x0001 ) == 0 ) bra ( c );
}

// **************************************************************************************
static opcode_t opcodes[256] = {
    /* 00 */
    {imp, brk, 7},
    {indx, ora, 6},
    {imp, nop, 2},
    {indx, slo, 8},
    {zp, tsb, 5},
    {zp, ora, 3},
    {zp, asl, 5},
    {zp, slo, 5},
    {imp, php, 3},
    {imm, ora, 2},
    {acc, asl, 2},
    {imm, nop, 2},
    {abso, tsb, 6},
    {abso, ora, 4},
    {abso, asl, 6},
    {rel_zp, bbr0, 6},
    /* 01 */
    {rel, bpl, 2},
    {indy_p, ora, 5},
    {zpi, ora, 5},
    {indy, slo, 8},
    {zp, trb, 5},
    {zpx, ora, 4},
    {zpx, asl, 6},
    {zpx, slo, 6},
    {imp, clc, 2},
    {absy_p, ora, 4},
    {acc, inc, 2},
    {absy, slo, 7},
    {abso, trb, 6},
    {absx_p, ora, 4},
    {absx, asl, 7},
    {absx, slo, 7},
    /* 02 */
    {abso, jsr, 6},
    {indx, and, 6},
    {imp, nop, 2},
    {indx, rla, 8},
    {zp, bit, 3},
    {zp, and, 3},
    {zp, rol, 5},
    {zp, rla, 5},
    {imp, plp, 4},
    {imm, and, 2},
    {acc, rol, 2},
    {imm, nop, 2},
    {abso, bit, 4},
    {abso, and, 4},
    {abso, rol, 6},
    {abso, rla, 6},
    /* 30 */
    {rel, bmi, 2},
    {indy_p, and, 5},
    {zpi, adc, 5},
    {indy, rla, 8},
    {zpx, bit, 4},
    {zpx, and, 4},
    {zpx, rol, 6},
    {zpx, rla, 6},
    {imp, sec, 2},
    {absy_p, and, 4},
    {acc, dec, 2},
    {absy, rla, 7},
    {absx_p, bit, 4},
    {absx_p, and, 4},
    {absx, rol, 7},
    {absx, rla, 7},
    /* 40 */
    {imp, rti, 6},
    {indx, eor, 6},
    {imp, nop, 2},
    {indx, sre, 8},
    {zp, nop, 3},
    {zp, eor, 3},
    {zp, lsr, 5},
    {zp, sre, 5},
    {imp, pha, 3},
    {imm, eor, 2},
    {acc, lsr, 2},
    {imm, nop, 2},
    {abso, jmp, 3},
    {abso, eor, 4},
    {abso, lsr, 6},
    {abso, sre, 6},
    /* 50 */
    {rel, bvc, 2},
    {indy_p, eor, 5},
    {zpi, eor, 5},
    {indy, sre, 8},
    {zpx, nop, 4},
    {zpx, eor, 4},
    {zpx, lsr, 6},
    {zpx, sre, 6},
    {imp, cli, 2},
    {absy_p, eor, 4},
    {imp, phy, 2},
    {absy, sre, 7},
    {absx, nop, 4},
    {absx_p, eor, 4},
    {absx, lsr, 7},
    {absx, sre, 7},
    /* 60 */
    {imp, rts, 6},
    {indx, adc, 6},
    {imp, nop, 2},
    {indx, rra, 8},
    {zp, stz, 3},
    {zp, adc, 3},
    {zp, ror, 5},
    {zp, rra, 5},
    {imp, pla, 4},
    {imm, adc, 2},
    {acc, ror, 2},
    {imm, nop, 2},
    {absi, jmp, 5},
    {abso, adc, 4},
    {abso, ror, 6},
    {abso, rra, 6},
    /* 70 */
    {rel, bvs, 2},
    {indy_p, adc, 5},
    {zpi, adc, 5},
    {indy, rra, 8},
    {zpx, stz, 4},
    {zpx, adc, 4},
    {zpx, ror, 6},
    {zpx, rra, 6},
    {imp, sei, 2},
    {absy_p, adc, 4},
    {imp, ply, 6},
    {absy, rra, 7},
    {absxi, jmp, 6},
    {absx_p, adc, 4},
    {absx, ror, 7},
    {absx, rra, 7},
    /* 80 */
    {rel, bra, 3},
    {indx, sta, 6},
    {imm, nop, 2},
    {indx, sax, 6},
    {zp, sty, 3},
    {zp, sta, 3},
    {zp, stx, 3},
    {zp, sax, 3},
    {imp, dey, 2},
    {imm, bit_imm, 2},
    {imp, txa, 2},
    {imm, nop, 2},
    {abso, sty, 4},
    {abso, sta, 4},
    {abso, stx, 4},
    {abso, sax, 4},
    /* 90 */
    {rel, bcc, 2},
    {indy, sta, 6},
    {zpi, sta, 5},
    {indy, nop, 6},
    {zpx, sty, 4},
    {zpx, sta, 4},
    {zpy, stx, 4},
    {zpy, sax, 4},
    {imp, tya, 2},
    {absy, sta, 5},
    {imp, txs, 2},
    {absy, nop, 5},
    {abso, stz, 4},
    {absx, sta, 5},
    {absx, stz, 5},
    {absy, nop, 5},
    /* A0 */
    {imm, ldy, 2},
    {indx, lda, 6},
    {imm, ldx, 2},
    {indx, lax, 6},
    {zp, ldy, 3},
    {zp, lda, 3},
    {zp, ldx, 3},
    {zp, lax, 3},
    {imp, tay, 2},
    {imm, lda, 2},
    {imp, tax, 2},
    {imm, nop, 2},
    {abso, ldy, 4},
    {abso, lda, 4},
    {abso, ldx, 4},
    {abso, lax, 4},
    /* B0 */
    {rel, bcs, 2},
    {indy_p, lda, 5},
    {zpi, lda, 5},
    {indy_p, lax, 5},
    {zpx, ldy, 4},
    {zpx, lda, 4},
    {zpy, ldx, 4},
    {zpy, lax, 4},
    {imp, clv, 2},
    {absy_p, lda, 4},
    {imp, tsx, 2},
    {absy_p, lax, 4},
    {absx_p, ldy, 4},
    {absx_p, lda, 4},
    {absy_p, ldx, 4},
    {absy_p, lax, 4},
    /* C0 */
    {imm, cpy, 2},
    {indx, cmp, 6},
    {imm, nop, 2},
    {indx, dcp, 8},
    {zp, cpy, 3},
    {zp, cmp, 3},
    {zp, dec, 5},
    {zp, dcp, 5},
    {imp, iny, 2},
    {imm, cmp, 2},
    {imp, dex, 2},
    {imm, nop, 2},
    {abso, cpy, 4},
    {abso, cmp, 4},
    {abso, dec, 6},
    {abso, dcp, 6},
    /* D0 */
    {rel, bne, 2},
    {indy_p, cmp, 5},
    {zpi, cmp, 5},
    {indy, dcp, 8},
    {zpx, nop, 4},
    {zpx, cmp, 4},
    {zpx, dec, 6},
    {zpx, dcp, 6},
    {imp, cld, 2},
    {absy_p, cmp, 4},
    {imp, phx, 3},
    {absy, dcp, 7},
    {absx, nop, 4},
    {absx_p, cmp, 4},
    {absx, dec, 7},
    {absx, dcp, 7},
    /* E0 */
    {imm, cpx, 2},
    {indx, sbc, 6},
    {imm, nop, 2},
    {indx, isb, 8},
    {zp, cpx, 3},
    {zp, sbc, 3},
    {zp, inc, 5},
    {zp, isb, 5},
    {imp, inx, 2},
    {imm, sbc, 2},
    {imp, nop, 2},
    {imm, sbc, 2},
    {abso, cpx, 4},
    {abso, sbc, 4},
    {abso, inc, 6},
    {abso, isb, 6},
    /* F0 */
    {rel, beq, 2},
    {indy_p, sbc, 5},
    {zpi, sbc, 5},
    {indy, isb, 8},
    {zpx, nop, 4},
    {zpx, sbc, 4},
    {zpx, inc, 6},
    {zpx, isb, 6},
    {imp, sed, 2},
    {absy_p, sbc, 4},
    {imp, plx, 2},
    {absy, isb, 7},
    {absx, nop, 4},
    {absx_p, sbc, 4},
    {absx, inc, 7},
    {absx, isb, 7}
};
#endif



